[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
  command = "npm run build"
  publish = ".next"
  environment = { NEXT_DISABLE_NETLIFY_EDGE = "true" }

[dev]
  command = "npm run dev"
  port = 3000 