[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
  command = "npm run build"
  publish = ".next"

[functions]

  [functions.edge_functions]
  # Edge functions configuration for Next.js middleware

[dev]
  command = "npm run dev"
  port = 3000 